### ISSUE TITLE
CSS menu style guide —— #1

### ISSUE THREAD

**Issue by nie-xin** [nie-xin/blog#3]
本人的CSS一直是战五渣的水平。最近在撸公司的CMS，但市场组一直对那个border-bottom的菜单叨逼叨。我也承认简单的border方案过于简陋了，于是就在Github上找了一组还算不错的参考，准备致敬一下 :)

俗话说，读书人的事儿，不能算抄。但简单的抄对自己毫无意义，更重要的是明白人家的为什么好，学会其中的原理来举一反三。下面就让我挑几个来分析一下吧。

首先是[Alonso](http://tympanus.net/Development/LineMenuStyles/#Alonso)，这是我最开始想选的方案，简洁大方。虽然后来发现他只适用于背景颜色单一的场景而没有采用，但他的确给了我不少启示。

该方案的HTML结构有些特殊：

``` html

<nav class="menu menu--alonso">
    <ul class="menu__list">
        <li class="menu__item"><a href="#" class="menu__link">Home</a></li>
        <li class="menu__item"><a href="#" class="menu__link">Gallery</a></li>
        <li class="menu__item"><a href="#" class="menu__link">Portfolio</a></li>
        <li class="menu__item"><a href="#" class="menu__link">Clients</a></li>
        <li class="menu__item menu__item--current"><a href="#" class="menu__link">Contact</a></li>
        <li class="menu__line"></li>
    </ul>
</nav>
```

在常规的ul最后多了一个内容为空的li，从class的名字`menu__line`就可以猜到这就是整个菜单滑动的下划线了，整个菜单就围绕这个实现下划线的滑动。

让我们来看看CSS部分吧，我只分析关键部分，完成代码可参考前面的链接。

``` css

.menu--alonso .menu__link {
    width: 120px;
    height: 3em;
    text-align: center;
    color: #b5b5b5;
    -webkit-transition: color 0.3s;
    transition: color 0.3s;
}

.menu--alonso .menu__link:hover,
.menu--alonso .menu__link:focus {
    color: #929292;
}

```

`menu__link` 就是菜单的选项了，比较重要的是定义了颜色的transition和时间0.3s，于是在发生hover和focus的时候，颜色的转换就会有一个0.3秒的持续时间，让颜色转换比较平滑。

``` css
.menu--alonso .menu__item--current .menu__link {
    color: #d94f5c;
    -webkit-transition: color 0.5s;
    transition: color 0.5s;
}
```

`menu__item--current`是当前激活的选项，与上面类似的颜色转换时间。

下面的`menu__line`是整个方案的重点：

``` css
.menu--alonso .menu__line {
    position: absolute;
    top: 100%;
    left: 0;
    width: 120px;
    height: 2px;
    pointer-events: none;
    border: 1px solid #fff;
    border-width: 0 45px;
    background: #d94f5c;
    -webkit-transition: -webkit-transform 0.5s;
    transition: transform 0.5s;
    -webkit-transition-timing-function: cubic-bezier(1, 0.01, 0, 1);
    -webkit-transition-timing-function: cubic-bezier(1, 0.01, 0, 1.22);
    transition-timing-function: cubic-bezier(1, 0.01, 0, 1.22);
}
```

本来`menu__line`也是ul的一个子元素，为了将他做成主选项的下划线，使用了position: absolute来调整位置（ul是有relative属性的）： `top: 100%; left: 0;`将它放到整个ul的最左下方，并且由于他和其他选项一直的width，他会和第一个menu__item完全对齐。之后还加入`pointer-event: none`来防止对这个li的点击事件。

下面是个有趣的地方：

``` css
    border: 1px solid #fff;
    border-width: 0 45px;
    background: #d94f5c;
```

这就是我一开始说的这个方案只适用于纯色背景的原因所在了。前面定义了该li的height为2px，这里则定义了border的宽度为1px，上下border加起来刚好是2px。然后左右border-width各为45px的白色，给中间留下了30px长，2px高的橘红色长条，从视觉上看就是一个中间对齐的下划线了。两个45px的白色刚好是demo背景的颜色，所以视觉上只看得到中间的下划线了。当背景是其他纯色的时候，只要改变border的颜色就可以了。但我们的背景是图片，所以这个方案最终没有被我采用。

最下面的几句是滑动该下划线的动画实现：

``` css

    -webkit-transition: -webkit-transform 0.5s;
    transition: transform 0.5s;
    -webkit-transition-timing-function: cubic-bezier(1, 0.01, 0, 1);
    -webkit-transition-timing-function: cubic-bezier(1, 0.01, 0, 1.22);
    transition-timing-function: cubic-bezier(1, 0.01, 0, 1.22);

```

为了transform平滑，加上了时延0.5s和一个特殊的时延函数[cubic-bezier](http://cubic-bezier.com/#.17,.67,.83,.67)。

下面就是下划线的滑动部分了：

``` css

.menu--alonso .menu__item:nth-child(1).menu__item--current ~ .menu__line {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
}

.menu--alonso .menu__item:nth-child(2).menu__item--current ~ .menu__line {
    -webkit-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0);
}

.menu--alonso .menu__item:nth-child(3).menu__item--current ~ .menu__line {
    -webkit-transform: translate3d(200%, 0, 0);
    transform: translate3d(200%, 0, 0);
}

```

根据选中选项在整个菜单的位置来移动下划线的x位置，第一个移动到0，第二个右移整个li的长度，也相当于将li右移了一格；第三个移动两格，以此类推。translate3d主要是为了激活硬件加速，提高动画性能。这部分style和layout耦合过于紧密，有许多重复代码，并不容易维护。

好了，让我们小结一下这个方案吧：
- 在菜单的ul中增加一个空的li作为滑动下划线
- 调增li的位置和长度，使其和菜单选项对齐
- 使用border和background来调整下划线的长度
- 根据当前激活选项在菜单中的位置，使用translate3d在x轴上移动下划线
- 适量加入transition动画时延，使各种变换更加平滑
