### ISSUE TITLE
今天学到的——#3

### ISSUE THREAD

**Issue by nie-xin** [nie-xin/blog#6]
pseudo元素默认是无法被transform的。这是因为pseudo元素默认是inline元素，inline元素无法被transform。做transform前需要加入`display: inline-block;`改变元素的显示属性才行：

``` css

.sub-menu::before {
  content: "\25e2";
  display: inline-block;
  position: relative;
  top: -1.7em;
  left: 2em;
  color: white;
  transform: rotate(-135deg);
}

```

利用rotate给下拉菜单增加一个指向上方的粗箭头。
